### ISSUE TITLE
Synch Fualt One drive

### ISSUE THREAD

**Issue by Pier74** [moneymanagerex/android-money-manager-ex#1370]
I' using your app on an android Phone and also with a pc win10, sharing the file toward Onedrive service. The PC save the file fine. The problem is on the mobile phone, because, when the app starts, doesn't read automatically the file from Onedrive. To do this I need to open in manually as new file, and so al voices are updated.

**Comment by wolfsolver** [comment]
Also I have same issue.

Moto g100
Android 12

**Comment by guanlisheng** [comment]
@wolfsolver can you share more on the your android mmex version. it should work with oneDrive.

**Comment by wolfsolver** [comment]
Hi @guanlisheng first at all Kudos to you for reborn this app!
I made some test to reproduce the issue on a clean db.
The issue can be recreate follow this step:
1. create empty db on windows and save to onedrive
2. create new account
3. create new trasaction (for example deposit 100)
4. save and close app
5. on android open ammx (fresh install, or delete befor all data) and open saved file
6. add new transaction (for example -10)
7. on Android make Sync (wait for toast notification remote file update)
8. check and see that remote file has been updare and synced on PC (<img width="269" alt="image" src="https://github.com/moneymanagerex/android-money-manager-ex/assets/3205448/a184cd87-d5cc-4337-ae35-9451dc99bd4e"> (note "Scaricato in Shared" means that onedrive has download file on pc)
9. Reopen file on PC and take a look to new transaction (-10) create on android
10. add new transaction -20 from pc
11. save and wait for onedrive upload <img width="265" alt="image" src="https://github.com/moneymanagerex/android-money-manager-ex/assets/3205448/09e353ca-1e27-4fdf-aca8-97501730f6af"> (note that "Caricato in Share" means that onedrive upload file on cloud)
12. open on android, file has not the new transaction -20
13. try to force sync (make it twice, don't know if is a delay in update or issue)
14. file correct update by toast notification (minor issue, if you made sync from account detail you didn't see new trasaction, you need to go home and re-select the account to see new transaction)
15. add new transaction on android with -30
16. make sync and toas message said "Conflict! both file has been modified" (but I'm sure that no one else has touch file while I operate on android)

here LogCat & Sample DB in zip file [test.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/13841569/test.zip)
you can find error message 
> "01-05 12:44:40.063  5050  5050 E FileStorageHelper: Conflict! Both files have been modified."

seems that is irrilevant if i try using "keep offline" on Onedrive on Android

thanks

**Comment by guanlisheng** [comment]
step 12 result is weird. we expect to see the new transaction (-20).

what's force sync in step 13?  manually click the main menu -> synchronize?

**Comment by wolfsolver** [comment]
> step 12 result is weird. we expect to see the new transaction (-20).
Means something like auto sync?

> what's force sync in step 13?  manually click the main menu -> synchronize?
Yes. Force sync by menu->synchronize.

**Comment by guanlisheng** [comment]
just found this issue from oneDrive, maybe you can adjust the oneDrive client as the article suggested
https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-is-changing-my-files-modified-date-when-i/29a97262-bc23-41b4-a477-11646d1a3ccc

**Comment by guanlisheng** [comment]
seems there are some reports from oneDrive of changing the modified time incorrectly. this might be the root cause.
https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-correct-the-date-modified-metadata-of/35f70450-01f1-4c7e-9d33-63151d2386d8

**Comment by guanlisheng** [comment]
after a detailed review, I think I addressed the bug in updating remoteLastChangedDate. 

@wolfsolver, can you help to verify via 2024.01.05.1010

**Comment by wolfsolver** [comment]
Mmm still present. Tomorrow I perform some deep test a take a look to documentation for OneDrive, and make some test also with Google to see comparison.

It's all ok until step 14 (no manual sync necessary if app closed), but conflict still present.

**Comment by wolfsolver** [comment]
Bad news :( it's  not realte to onedrive issue. 
Same beaviours with google drive. After add transaction on mobile, message error (conflict) even if no change are made on remote db. Unfortunately in logcat there is no much info. 

Any suggest to how debug or trace info?

**Comment by guanlisheng** [comment]
thanks @wolfsolver , please re-install the latest package uploaded about 24 hours ago.  the previous one had some issues...

**Comment by wolfsolver** [comment]
👌! Good job! seems working. I notice a strange behaviour in a test, but maybe it was becouse I didn't wait for remote upload. 
I will keep it monitored to see if is all ok. 
- [X] test with OneDrive: ok
- [X] test with gDrive: ok

I set "stale" label, since no news was good news :-)
