### ISSUE TITLE
Unable to view closed accounts

### ISSUE THREAD

**Issue by smjohns** [moneymanagerex/android-money-manager-ex#1881]
**Describe the bug**
When I go into Settings>Look&feel and remove the tick from the "view open accounts" tick box I'm expecting to see all my closed accounts but the app is not displaying them and I have no means to view them.

The only way to view a closed account is to edit the account entity and change it from closed to open and then mark out closed again.

**To Reproduce**
As above. 

**Expected behavior**
When the look and feel open account setting is untucked all closed accounts should be visible.

**Screenshots**
Can provide if required

**Device Information:**
 - Device: Samsung Galaxy S22
 - OS: Android 14
 - Storage: 256gb
 - Synchronisation: Interval = never and set to sync on open.
 - Encrypted: no
 - Security: passcode and fingerprint
 - App Version: 2024.11.10-Android (1044)

**Additional context**
N/A

**Comment by guanlisheng** [comment]
thanks @smjohns for trying MMEX on Google Play.

we have addressed the bug and will roll out a fix in the coming releases.

**Comment by smjohns** [comment]
Just tried it but closed accounts are still not visible regardless of the look and feel setting. Only way to view closed accounts is to open them again.

**Comment by smjohns** [comment]
On Google Play 22-11-2024 1048 and this is now working. Thanks for help on this.
